[package]
name = "rp-pio"
description = "Support library for handling PIO programs for the Programmable Input/Output peripheral found in Raspberry Silicon microcontrollers"
license = "MIT"
version = "0.1.0"
authors = ["snek"]
edition = "2018"
resolver = "2"

[workspace]
members = ["pio-proc", "pio-parser"]

[dependencies]
arrayvec = { version = "0.7", default_features = false }
paste = "1.0"
num_enum = { version = "0.5", default_features = false }

[dev-dependencies]
test-generator = "0.3.0"
pretty_assertions = "0.6"
rp-pio-proc = { path = "./pio-proc" }
rp-pio-parser = { path = "./pio-parser" }
